#spring:
#  profiles:
#    active: dev
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring-boot-test?useSSL=false&characterEncoding=utf-8
    username: root
    password: root
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

mybatis:
  type-aliases-package: com.jin.auth.entity,com.jin.girl.entity
  mapper-locations: classpath:mappers/**/*.xml
#  check-config-location: true
  config-locations: classpath:mybatis/mybatis-config.xml
#  createSqlSessionTemplate: false



logging:
  level:
    root: info
    com:
      jin:
        auth:
          dao: debug
        girl:
          dao: debug
  pattern:
    console: d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n

